# PROJECT TRACKING SYSTEM API

###
# group: POPULATE
# @name Populate
POST {{URL}}/populate
Content-Type: application/json

{
  "task": "insert mock data"
}

###
# group: Auth
# @name Register
POST {{URL}}/auth/register
Content-Type: application/json

{
  "username": "newbarangay",
  "password": "Qetwr13524!",
  "email": "newbarangay@gmail.com",
  "role": "barangay",
  "barangay_id": 112
}

###
# group: Auth
# @name Login
POST {{URL}}/auth/login
Content-Type: application/json

{
  "email": "smcturlough30@163.com",
  "password": "rA0!>E"
}

###
# group: Auth
# @name Logout
DELETE {{URL}}/auth/logout

###
# group: Auth
# @name Forgot Password
POST {{URL}}/auth/forgot-password
Content-Type: application/json

{
  "email": "gierhansclement@gmail.com"
}

###
# group: Auth
# @name Reset Password
POST {{URL}}/auth/reset-password
Content-Type: application/json

{
  "email": "gierhansclement@gmail.com",
  "password": "Qetwr13524!!",
  "token": "7GNgw9inqs5SXRJz2du8sMSEUIjk1-nat5Y1"
}

###
# group: User
# @name Get All Users
GET {{URL}}/users?
    search=hans&
    sort=-username&
    role=barangays&
    banned=false&
    page=1&
    limit=10&
    barangayId=2
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary

--WebAppBoundary

###
# group: User
# @name Get User
GET {{URL}}/users/{{id_1}}

###
# group: User
# @name Show Current User
GET {{URL}}/users/me

###
# group: User
# @name Update User
PATCH {{URL}}/users/update-user
Content-Type: application/json

{
  "username": "hansgier",
  "email": ""
}

###
# group: User
# @name Update User Password
PATCH {{URL}}/users/update-user-password
Content-Type: application/json

{
  "oldPassword": "Qetwr13524!!",
  "newPassword": "Qetwr13524!"
}

###
# group: User
# @name Delete User
DELETE {{URL}}/users/{{id_2}}

###
# group: User
# @name Delete All Users
DELETE {{URL}}/users

###
# group: Barangay
# @name Populate Barangay
POST {{URL}}/barangays/populate

###
# group: Barangay
# @name Add Barangay
POST {{URL}}/barangays
Content-Type: application/json

{
  "name": "Tambulilid"
}

###
# group: Barangay
# @name Get All Barangays
GET {{URL}}/barangays?
    search=ale&
    sort=&
    page=1&
    limit=5

###
# group: Barangay
# @name Get Barangay
GET {{URL}}/barangays/{{id_3}}

###
# group: Barangay
# @name Delete All Barangays
DELETE {{URL}}/barangays

###
# group: Barangay
# @name Delete Barangay
DELETE {{URL}}/barangays/{{id_4}}

###
# group: Barangay
# @name Update Barangay
PATCH {{URL}}/barangays/{{id_5}}
Content-Type: application/json

{
  "name": "tae ko"
}

###
# group: Project
# @name Add Project
POST {{URL}}/projects
Content-Type: application/json

{
  "title": "charity 1",
  "description": "JYJTDSRGAGHJDTSRETYRTYWERGDFGSRTQWEFGDHSRTYWERGDFHSTYAERg",
  "objectives": "1. To widening the roads 2. to road 3. taeta",
  "cost": 2000000.00,
  "start_date": "2023-10-23 08:45:21",
  "due_date": "2024-10-23 08:45:21",
  "completion_date": "2024-10-23 08:45:21",
  "status": "not_started",
  "progress": 45,
  "views": 100,
  "barangayIds": [],
  "tags": [
    {
      "name": "general_public_services"
    },
    {
      "name": "health"
    },
    {
      "name": "infrastructure"
    }
  ]
}

###
# group: Project
# @name Get All Projects
GET {{URL}}/projects?
    tags=general_public_services&
    barangays=1&
    status=completed&
    sort=progress&
    costRange=1000-10000&
    progressRange=>&
    viewsRange=<45&
    page=1&
    limit=10

> {%
    // TODO: you can add here Response handler
%}

###
# group: Project
# @name Delete All Projects
DELETE {{URL}}/projects

###
# group: Project
# @name Update Project
PATCH {{URL}}/projects/{{id_6}}
Content-Type: application/json

{
  "start_date": "2024-8-23 08:45:21",
  "due_date": "2024-10-23 08:45:21",
  "completion_date": "2024-12-23 08:45:21",
  "barangayIds": [],
  "tagsIds": []
}

###
# group: Project
# @name Get Project
GET {{URL}}/projects/{{id_7}}

###
# group: Project
# @name Delete Project
DELETE {{URL}}/projects/{{id_8}}

###
# group: Comment
# @name Post Comment
POST {{URL}}/projects/{{id_9}}/comments

###
# group: Comment
# @name Edit Project Comment
PATCH {{URL}}/projects/{{id_10}}/comments/{{commentId_1}}

###
# group: Comment
# @name Get All Project Comments
GET {{URL}}/projects/{{id_11}}/comments

###
# group: Comment
# @name Delete Project Comment
DELETE {{URL}}/projects/{{id_12}}/comments/{{commentId_2}}

###
# group: Comment
# @name Get All Comments
GET {{URL}}/comments

###
# group: Comment
# @name Get Comment
GET {{URL}}/comments/{{id_13}}

###
# group: Comment
# @name Delete All Comments
DELETE {{URL}}/comments

###
# group: Comment
# @name Delete Comment
DELETE {{URL}}/comments/{{id_14}}