module.exports = [
    { name: 'Airport' },
    { name: 'Alegria' },
    { name: 'Alta Vista' },
    { name: 'Bagong' },
    { name: 'Bagong Buhay' },
    { name: 'Bantigue' },
    { name: 'Barangay 1' },
    { name: 'Barangay 10' },
    { name: 'Barangay 11' },
    { name: 'Barangay 12' },
    { name: 'Barangay 13' },
    { name: 'Barangay 14' },
    { name: 'Barangay 15' },
    { name: 'Barangay 16' },
    { name: 'Barangay 17' },
    { name: 'Barangay 18' },
    { name: 'Barangay 19' },
    { name: 'Barangay 2' },
    { name: 'Barangay 20' },
    { name: 'Barangay 21' },
    { name: 'Barangay 22' },
    { name: 'Barangay 23' },
    { name: 'Barangay 24' },
    { name: 'Barangay 25' },
    { name: 'Barangay 26' },
    { name: 'Barangay 27' },
    { name: 'Barangay 28' },
    { name: 'Barangay 29' },
    { name: 'Barangay 3' },
    { name: 'Barangay 4' },
    { name: 'Barangay 5' },
    { name: 'Barangay 6' },
    { name: 'Barangay 7' },
    { name: 'Barangay 8' },
    { name: 'Barangay 9' },
    { name: 'Batuan' },
    { name: 'Bayog' },
    { name: 'Biliboy' },
    { name: 'Borok' },
    { name: 'Cabaon-an' },
    { name: 'Cabintan' },
    { name: 'Cabulihan' },
    { name: 'Cagbuhangin' },
    { name: 'Camp Downes' },
    { name: 'Can-adieng' },
    { name: 'Can-untog' },
    { name: 'Catmon' },
    { name: 'Cogon Combado' },
    { name: 'Concepcion' },
    { name: 'Curva' },
    { name: 'Danao' },
    { name: 'Danhug' },
    { name: 'Dayhagan' },
    { name: 'Dolores' },
    { name: 'Domonar' },
    { name: 'Don Felipe Larrazabal' },
    { name: 'Don Potenciano Larrazabal' },
    { name: 'Doña Feliza Z. Mejia' },
    { name: 'Donghol' },
    { name: 'Esperanza' },
    { name: 'Gaas' },
    { name: 'Green Valley' },
    { name: 'Guintigui-an' },
    { name: 'Hibunawon' },
    { name: 'Hugpa' },
    { name: 'Ipil' },
    { name: 'Juaton' },
    { name: 'Kadaohan' },
    { name: 'Labrador' },
    { name: 'Lao' },
    { name: 'Leondoni' },
    { name: 'Libertad' },
    { name: 'Liberty' },
    { name: 'Licuma' },
    { name: 'Liloan' },
    { name: 'Linao' },
    { name: 'Luna' },
    { name: 'Mabato' },
    { name: 'Mabini' },
    { name: 'Macabug' },
    { name: 'Magaswi' },
    { name: 'Mahayag' },
    { name: 'Mahayahay' },
    { name: 'Manlilinao' },
    { name: 'Margen' },
    { name: 'Mas-in' },
    { name: 'Matica-a' },
    { name: 'Milagro' },
    { name: 'Monterico' },
    { name: 'Nasunogan' },
    { name: 'Naungan' },
    { name: 'Nueva Sociedad' },
    { name: 'Nueva Vista' },
    { name: 'Patag' },
    { name: 'Punta' },
    { name: 'Quezon, Jr.' },
    { name: 'Rufina M. Tan' },
    { name: 'Sabang Bao' },
    { name: 'Salvacion' },
    { name: 'San Antonio' },
    { name: 'San Isidro' },
    { name: 'San Jose' },
    { name: 'San Juan' },
    { name: 'San Pablo' },
    { name: 'San Vicente' },
    { name: 'Santo Niño' },
    { name: 'Sumangga' },
    { name: 'Tambulilid' },
    { name: 'Tongonan' },
    { name: 'Valencia' },
    { name: 'Guest' },
];