module.exports = [
    {
        username: "City Government",
        password: "1j28ifZa4#ge%raF",
        email: "systemadmin@admin.com",
        role: "admin",
    },
    {
        username: "hans",
        password: "Qetwr13524!",
        email: "hans@email.com",
        role: "resident",
        barangay_id: 67,
    },
    {
        username: "von",
        password: "uG5|dw.}wKp1",
        email: "von@email.com",
        role: "resident",
        barangay_id: 59,
    },
    {
        username: "bnice9d",
        password: "fU1<#3&",
        email: "eschule9d@java.com",
        role: "resident",
        barangay_id: 29,
    },
    {
        username: "hniesel9e",
        password: "oF8,{?6C",
        email: "smorillas9e@state.gov",
        role: "resident",
        barangay_id: 18,
    },
    {
        username: "vmcphelimy9f",
        password: "mC7+70B$l_P5",
        email: "sraynard9f@zdnet.com",
        role: "resident",
        barangay_id: 66,
    },
    {
        username: "jdearan9g",
        password: "kD9/<wD",
        email: "gchudleigh9g@stumbleupon.com",
        role: "resident",
        barangay_id: 68,
    },
    {
        username: "oshilstone9h",
        password: "fT7@l/",
        email: "ngeindre9h@jalbum.net",
        role: "resident",
        barangay_id: 17,
    },
    {
        username: "pbinner9i",
        password: "xC4at3v6",
        email: "mmerrin9i@marketwatch.com",
        role: "resident",
        barangay_id: 58,
    },
    {
        username: "dcampana9j",
        password: "yL0*b.7r",
        email: "adrillingcourt9j@mlb.com",
        role: "resident",
        barangay_id: 16,
    },
    {
        username: "kdrinkwater9k",
        password: "lA33uS0RWQ",
        email: "bkilborn9k@storify.com",
        role: "resident",
        barangay_id: 17,
    },
    {
        username: "lmccaull9l",
        password: "rK6_jMGj}r",
        email: "aparadin9l@typepad.com",
        role: "resident",
        barangay_id: 68,
    },
    {
        username: "pyeomans9m",
        password: "aK4>_HC8",
        email: "aleyre9m@theglobeandmail.com",
        role: "resident",
        barangay_id: 83,
    },
    {
        username: "cpauly9n",
        password: "vK1>KYc",
        email: "fmacneillie9n@jugem.jp",
        role: "resident",
        barangay_id: 7,
    },
    {
        username: "crosina9o",
        password: "qJ2_wo70R",
        email: "hwinckworth9o@hubpages.com",
        role: "resident",
        barangay_id: 103,
    },
    {
        username: "tvyse9p",
        password: "aY2'.HZF",
        email: "scasaroli9p@blogtalkradio.com",
        role: "resident",
        barangay_id: 2,
    },
    {
        username: "tosan9q",
        password: "vY4}nlat,",
        email: "mpaynton9q@upenn.edu",
        role: "resident",
        barangay_id: 96,
    },
    {
        username: "hwindas9r",
        password: "fY3)zSFf",
        email: "wklee9r@hubpages.com",
        role: "resident",
        barangay_id: 103,
    },
    {
        username: "nroo9s",
        password: "cA6atIlPD`%>",
        email: "dverney9s@epa.gov",
        role: "resident",
        barangay_id: 108,
    },
    {
        username: "bromushkin9t",
        password: "eZ0=.'Q.R+",
        email: "jseabourne9t@bloomberg.com",
        role: "resident",
        barangay_id: 1,
    },
    {
        username: "kburrett9u",
        password: "dW4?B9g7",
        email: "pdyke9u@theglobeandmail.com",
        role: "resident",
        barangay_id: 49,
    },
    {
        username: "stortoise9v",
        password: "xP0$F+70h5Du",
        email: "bbeade9v@rambler.ru",
        role: "resident",
        barangay_id: 39,
    },
    {
        username: "acrittal9w",
        password: "eI4(NH6",
        email: "fhuttley9w@surveymonkey.com",
        role: "resident",
        barangay_id: 76,
    },
    {
        username: "lgollop9x",
        password: "eX1=6!WV{HE",
        email: "qaizik9x@ask.com",
        role: "resident",
        barangay_id: 108,
    },
    {
        username: "wjachimiak9y",
        password: "kO8?gB4",
        email: "fkaret9y@europa.eu",
        role: "resident",
        barangay_id: 19,
    },
    {
        username: "kharling9z",
        password: "rQ7%aUl",
        email: "dclarkin9z@studiopress.com",
        role: "resident",
        barangay_id: 67,
    },
    {
        username: "tmomerya0",
        password: "sO3)yH*aU&",
        email: "gticehursta0@istockphoto.com",
        role: "resident",
        barangay_id: 34,
    },
    {
        username: "mhatchetta1",
        password: "sU1#?bVZ|",
        email: "rverbruggea1@umich.edu",
        role: "resident",
        barangay_id: 87,
    },
    {
        username: "lcannana2",
        password: "hL5{/joc+P_",
        email: "deliea2@webs.com",
        role: "resident",
        barangay_id: 44,
    },
    {
        username: "glabrowa3",
        password: "wH7<npk,'(w1",
        email: "gbeckeya3@state.tx.us",
        role: "resident",
        barangay_id: 102,
    },
    {
        username: "imangiona4",
        password: "cR3/TY+Kl#",
        email: "bpecharda4@behance.net",
        role: "resident",
        barangay_id: 104,
    },
    {
        username: "jrigmanda5",
        password: "tO7`I>Nr+V",
        email: "vlinsteada5@hc360.com",
        role: "resident",
        barangay_id: 98,
    },
    {
        username: "hkika6",
        password: "jS23O3",
        email: "dcuerdalla6@unesco.org",
        role: "resident",
        barangay_id: 21,
    },
    {
        username: "lguerrazzia7",
        password: "xG3'ymm#(37",
        email: "galdrena7@ning.com",
        role: "resident",
        barangay_id: 93,
    },
    {
        username: "sharefoota8",
        password: "jI2'qp8qtkb",
        email: "rpantrya8@kickstarter.com",
        role: "resident",
        barangay_id: 103,
    },
    {
        username: "mvolkesa9",
        password: "hA9.0=/3Y",
        email: "rfidocka9@accuweather.com",
        role: "resident",
        barangay_id: 47,
    },
    {
        username: "lpressnellaa",
        password: "aN7*T!d+?&8",
        email: "rdulintyaa@businessinsider.com",
        role: "resident",
        barangay_id: 44,
    },
    {
        username: "astylesab",
        password: "zD0atk2_",
        email: "dmeugensab@instagram.com",
        role: "resident",
        barangay_id: 57,
    },
    {
        username: "bmeakerac",
        password: "pG370vTSW90o",
        email: "hbarrieac@oaic.gov.au",
        role: "resident",
        barangay_id: 5,
    },
    {
        username: "hsiveterad",
        password: "kR0`+mHMjatX",
        email: "rpervewad@bandcamp.com",
        role: "resident",
        barangay_id: 74,
    },
    {
        username: "rbreamae",
        password: "iH7@.+",
        email: "ihuntingtonae@economist.com",
        role: "resident",
        barangay_id: 73,
    },
    {
        username: "pdodimeadaf",
        password: "dD170x.",
        email: "hgeertsenaf@ft.com",
        role: "resident",
        barangay_id: 105,
    },
    {
        username: "nchaddag",
        password: "kZ4*4Kio}",
        email: "cbalmaag@dagondesign.com",
        role: "resident",
        barangay_id: 12,
    },
    {
        username: "fsummertonah",
        password: "nL5/`G3",
        email: "cwhittingtonah@sina.com.cn",
        role: "resident",
        barangay_id: 30,
    },
    {
        username: "lpoznanai",
        password: "bO5,F!kzI)r",
        email: "chazlewoodai@cocolog-nifty.com",
        role: "resident",
        barangay_id: 93,
    },
    {
        username: "gthomassonaj",
        password: "uO43<d70tP",
        email: "fbonteinaj@purevolume.com",
        role: "resident",
        barangay_id: 74,
    },
    {
        username: "smcmackinak",
        password: "wK53)z",
        email: "dfynnak@blog.com",
        role: "resident",
        barangay_id: 6,
    },
    {
        username: "cmottinellial",
        password: "qR4@E70$",
        email: "rskittrellal@linkedin.com",
        role: "resident",
        barangay_id: 24,
    },
    {
        username: "cgreaterexam",
        password: "tJ3)2m.}Oh",
        email: "tsimicam@msu.edu",
        role: "resident",
        barangay_id: 2,
    },
    {
        username: "zgorchan",
        password: "jN1}|9sDNor",
        email: "rwillean@etsy.com",
        role: "resident",
        barangay_id: 55,
    },
    {
        username: "vbascombeao",
        password: "vD8|eY01XD",
        email: "blacosteao@bloglines.com",
        role: "resident",
        barangay_id: 65,
    },
    {
        username: "mpickworthap",
        password: "mF2+0uw3vZ,0",
        email: "lwheatlandap@wiley.com",
        role: "resident",
        barangay_id: 15,
    },
    {
        username: "bboyingtonaq",
        password: "xT8!V1tC",
        email: "cnayloraq@g.co",
        role: "resident",
        barangay_id: 86,
    },
    {
        username: "tetchellar",
        password: "xM6(e(e{pDK",
        email: "bogormleyar@prlog.org",
        role: "resident",
        barangay_id: 96,
    },
    {
        username: "gwhawellas",
        password: "sV0=Y4%",
        email: "vmcelreaas@webs.com",
        role: "resident",
        barangay_id: 3,
    },
    {
        username: "ncornellat",
        password: "uE6+1{q3=a",
        email: "tjoslowat@trellian.com",
        role: "resident",
        barangay_id: 87,
    },
    {
        username: "bbayford0",
        password: "mM0|D0pmO7",
        email: "alitherland0@taobao.com",
        role: "barangay",
        barangay_id: 1,
    },
    {
        username: "mthomassin1",
        password: "lY7!Dt*G6V",
        email: "ijuszkiewicz1@unesco.org",
        role: "barangay",
        barangay_id: 2,
    },
    {
        username: "dsmallacombe2",
        password: "mQ4%j*MV",
        email: "kjennery2@mapy.cz",
        role: "barangay",
        barangay_id: 3,
    },
    {
        username: "gskip3",
        password: "tK6?qp14=ctd",
        email: "mvandendael3@unc.edu",
        role: "barangay",
        barangay_id: 4,
    },
    {
        username: "theatherington4",
        password: "nF0_c9Kt",
        email: "vmcnickle4@opensource.org",
        role: "barangay",
        barangay_id: 5,
    },
    {
        username: "rlinscott5",
        password: "vF1@ogf8",
        email: "cyendle5@over-blog.com",
        role: "barangay",
        barangay_id: 6,
    },
    {
        username: "spiesing6",
        password: "nC2@`n!kL%{}",
        email: "cmose6@artisteer.com",
        role: "barangay",
        barangay_id: 7,
    },
    {
        username: "ttellesson7",
        password: "bK2!H8)+EZw",
        email: "dmendes7@addthis.com",
        role: "barangay",
        barangay_id: 8,
    },
    {
        username: "cschubert8",
        password: "vA4@To>u3",
        email: "mduthie8@facebook.com",
        role: "barangay",
        barangay_id: 9,
    },
    {
        username: "bpeplay9",
        password: "oL8?5293@Oh",
        email: "dcurror9@google.it",
        role: "barangay",
        barangay_id: 10,
    },
    {
        username: "nfishendena",
        password: "eB73$n/QL",
        email: "jchampea@reuters.com",
        role: "barangay",
        barangay_id: 11,
    },
    {
        username: "sjancab",
        password: "eW6}Y$<m*",
        email: "crosewarneb@deliciousdays.com",
        role: "barangay",
        barangay_id: 12,
    },
    {
        username: "jbirdallc",
        password: "aP3,c,n3Jy",
        email: "cperigoec@wikia.com",
        role: "barangay",
        barangay_id: 13,
    },
    {
        username: "hhaeslierd",
        password: "yM1=qt{Fx2y",
        email: "askelcherd@arstechnica.com",
        role: "barangay",
        barangay_id: 14,
    },
    {
        username: "nmccreerye",
        password: "zC1}JZ",
        email: "fgoodchilde@mozilla.org",
        role: "barangay",
        barangay_id: 15,
    },
    {
        username: "gculbertf",
        password: "gS1$J1Wi(",
        email: "anaisbitf@ca.gov",
        role: "barangay",
        barangay_id: 16,
    },
    {
        username: "glightollersg",
        password: "jP8(a.{lnVR",
        email: "nearlesg@wisc.edu",
        role: "barangay",
        barangay_id: 17,
    },
    {
        username: "byanukh",
        password: "qE9>m970V2y",
        email: "edhenninh@patch.com",
        role: "barangay",
        barangay_id: 18,
    },
    {
        username: "barsnelli",
        password: "uZ4}z<sL*=oe",
        email: "mgrinnovi@wordpress.org",
        role: "barangay",
        barangay_id: 19,
    },
    {
        username: "mlangmuirj",
        password: "xU6!tzp",
        email: "pvitallj@symantec.com",
        role: "barangay",
        barangay_id: 20,
    },
    {
        username: "aleerek",
        password: "wC5(?d_{Rw",
        email: "sjeannequink@techcrunch.com",
        role: "barangay",
        barangay_id: 21,
    },
    {
        username: "cdebiaggil",
        password: "iF0>7Aat3`kat",
        email: "dperigol@umn.edu",
        role: "barangay",
        barangay_id: 22,
    },
    {
        username: "bgadesbym",
        password: "dL9{Ochq",
        email: "jmannakeem@answers.com",
        role: "barangay",
        barangay_id: 23,
    },
    {
        username: "ezanellin",
        password: "wD7&'DO7/0$W",
        email: "hmckintoshn@i2i.jp",
        role: "barangay",
        barangay_id: 24,
    },
    {
        username: "hramsdello",
        password: "dO6#k9tr",
        email: "hnimmoo@weather.com",
        role: "barangay",
        barangay_id: 25,
    },
    {
        username: "fpusillp",
        password: "mQ2!+&&#3?_",
        email: "cblazynskip@over-blog.com",
        role: "barangay",
        barangay_id: 26,
    },
    {
        username: "psenecauxq",
        password: "lG9{LD?7J*",
        email: "wsidnallq@godaddy.com",
        role: "barangay",
        barangay_id: 27,
    },
    {
        username: "eburetr",
        password: "uA437R4g",
        email: "belkinr@sina.com.cn",
        role: "barangay",
        barangay_id: 28,
    },
    {
        username: "lhatters",
        password: "dD1&P>&b,$",
        email: "ihalsos@nytimes.com",
        role: "barangay",
        barangay_id: 29,
    },
    {
        username: "apotteryt",
        password: "jD6'=Z}G?",
        email: "tmacmurrayt@ibm.com",
        role: "barangay",
        barangay_id: 30,
    },
    {
        username: "jyoslowitzu",
        password: "eL9(uqd",
        email: "tposseu@latimes.com",
        role: "barangay",
        barangay_id: 31,
    },
    {
        username: "egianottiv",
        password: "rB6*46iX(_Rf",
        email: "bstrondv@wunderground.com",
        role: "barangay",
        barangay_id: 32,
    },
    {
        username: "jaxelbeew",
        password: "gM5=PC",
        email: "jglaviasw@facebook.com",
        role: "barangay",
        barangay_id: 33,
    },
    {
        username: "ieyreex",
        password: "nQ5<MdF$jj!L",
        email: "dcallearx@sakura.ne.jp",
        role: "barangay",
        barangay_id: 34,
    },
    {
        username: "lcrothery",
        password: "dW5`#NmuhQ,%",
        email: "gowthwaitey@ucsd.edu",
        role: "barangay",
        barangay_id: 35,
    },
    {
        username: "swortsz",
        password: "kZ63Uiw{",
        email: "sbeavorsz@answers.com",
        role: "barangay",
        barangay_id: 36,
    },
    {
        username: "orucklidge10",
        password: "vO8`$j1",
        email: "pburnep10@sourceforge.net",
        role: "barangay",
        barangay_id: 37,
    },
    {
        username: "sparcells11",
        password: "tW2.L!mB&h7",
        email: "alemm11@ovh.net",
        role: "barangay",
        barangay_id: 38,
    },
    {
        username: "jstopp12",
        password: "tY6{v<fb|,5",
        email: "ablundon12@ehow.com",
        role: "barangay",
        barangay_id: 39,
    },
    {
        username: "mspacey13",
        password: "sO000VU}R",
        email: "rfearnehough13@mozilla.org",
        role: "barangay",
        barangay_id: 40,
    },
    {
        username: "krennison14",
        password: "fK9(>t9",
        email: "mgranleese14@java.com",
        role: "barangay",
        barangay_id: 41,
    },
    {
        username: "wshrubshall15",
        password: "bO4)L+)@JS",
        email: "mlambal15@timesonline.co.uk",
        role: "barangay",
        barangay_id: 42,
    },
    {
        username: "adonnachie16",
        password: "jH933&Y%9=D",
        email: "dmushawe16@bizjournals.com",
        role: "barangay",
        barangay_id: 43,
    },
    {
        username: "mconws17",
        password: "pS370xJ)jE5y",
        email: "nkeeton17@exblog.jp",
        role: "barangay",
        barangay_id: 44,
    },
    {
        username: "habbets18",
        password: "tP4_PW_QA",
        email: "casals18@phoca.cz",
        role: "barangay",
        barangay_id: 45,
    },
    {
        username: "csidworth19",
        password: "aZ3=UrTRjd<",
        email: "cmatfin19@youtu.be",
        role: "barangay",
        barangay_id: 46,
    },
    {
        username: "jsyseland1a",
        password: "lT0!yZ",
        email: "rcossar1a@skyrock.com",
        role: "barangay",
        barangay_id: 47,
    },
    {
        username: "edelayglesia1b",
        password: "lR4{<jkq>qX",
        email: "rbriddle1b@google.pl",
        role: "barangay",
        barangay_id: 48,
    },
    {
        username: "alille1c",
        password: "nJ7}e3R7",
        email: "agorger1c@storify.com",
        role: "barangay",
        barangay_id: 49,
    },
    {
        username: "lbamford1d",
        password: "oE9<atSOE",
        email: "fassiter1d@nymag.com",
        role: "barangay",
        barangay_id: 50,
    },
    {
        username: "kdorre1e",
        password: "pR5(ezG@",
        email: "lmoynihan1e@google.fr",
        role: "barangay",
        barangay_id: 51,
    },
    {
        username: "jbrightman1f",
        password: "fC7@4X@O",
        email: "asmeath1f@newyorker.com",
        role: "barangay",
        barangay_id: 52,
    },
    {
        username: "rredmore1g",
        password: "tT5Sq}+zg",
        email: "cwhittek1g@ezinearticles.com",
        role: "barangay",
        barangay_id: 53,
    },
    {
        username: "bstreight1h",
        password: "xE470}zwZ",
        email: "ksibbson1h@ning.com",
        role: "barangay",
        barangay_id: 54,
    },
    {
        username: "aharsent1i",
        password: "aP1}}<Dy",
        email: "rbeade1i@nps.gov",
        role: "barangay",
        barangay_id: 55,
    },
    {
        username: "bfearenside1j",
        password: "yR9@F0",
        email: "ngetch1j@over-blog.com",
        role: "barangay",
        barangay_id: 56,
    },
    {
        username: "nperrott1k",
        password: "tV9>7/X",
        email: "kosgordby1k@reference.com",
        role: "barangay",
        barangay_id: 57,
    },
    {
        username: "obeetham1l",
        password: "wZ6*T0p3satN",
        email: "hmatoshin1l@elpais.com",
        role: "barangay",
        barangay_id: 58,
    },
    {
        username: "aeayres1m",
        password: "aW9`js{Qq*X#",
        email: "mmunson1m@amazon.co.jp",
        role: "barangay",
        barangay_id: 59,
    },
    {
        username: "tnewsham1n",
        password: "fI778x",
        email: "bstandishbrooks1n@twitpic.com",
        role: "barangay",
        barangay_id: 60,
    },
    {
        username: "slovell1o",
        password: "eA3WI)R9",
        email: "bdannatt1o@ow.ly",
        role: "barangay",
        barangay_id: 61,
    },
    {
        username: "rmcgenn1p",
        password: "gN3_syGjiw",
        email: "aheijnen1p@nsw.gov.au",
        role: "barangay",
        barangay_id: 62,
    },
    {
        username: "sbryning1q",
        password: "lD9?#K(M",
        email: "wordemann1q@blogger.com",
        role: "barangay",
        barangay_id: 63,
    },
    {
        username: "fbontoft1r",
        password: "aL1_N2!1",
        email: "gbanke1r@youtube.com",
        role: "barangay",
        barangay_id: 64,
    },
    {
        username: "gmcclenan1s",
        password: "iU3#$a0_N+",
        email: "rcardoso1s@list-manage.com",
        role: "barangay",
        barangay_id: 65,
    },
    {
        username: "amaccardle1t",
        password: "uI3(N?IU",
        email: "iwillmore1t@paginegialle.it",
        role: "barangay",
        barangay_id: 66,
    },
    {
        username: "cswine1u",
        password: "sA6_ONPNR",
        email: "hkoppelmann1u@google.co.uk",
        role: "barangay",
        barangay_id: 67,
    },
    {
        username: "lkirstein1v",
        password: "fW1@q<_3(X4}",
        email: "btoquet1v@gmpg.org",
        role: "barangay",
        barangay_id: 68,
    },
    {
        username: "chaldin1w",
        password: "uC5)70mojV6!Y",
        email: "cbleier1w@nature.com",
        role: "barangay",
        barangay_id: 69,
    },
    {
        username: "rrodell1x",
        password: "aX4@ilc2p9",
        email: "mmatschuk1x@slate.com",
        role: "barangay",
        barangay_id: 70,
    },
    {
        username: "tdowgill1y",
        password: "pL4<K=",
        email: "yconboy1y@xing.com",
        role: "barangay",
        barangay_id: 71,
    },
    {
        username: "idoxsey1z",
        password: "fE9<yWmdeu",
        email: "mbowland1z@wp.com",
        role: "barangay",
        barangay_id: 72,
    },
    {
        username: "aangeau20",
        password: "yY7?7O5f%M",
        email: "ivannah20@gnu.org",
        role: "barangay",
        barangay_id: 73,
    },
    {
        username: "mroxburch21",
        password: "uP7aOi",
        email: "plorkings21@linkedin.com",
        role: "barangay",
        barangay_id: 74,
    },
    {
        username: "sgoulbourn22",
        password: "kG4{L8Z",
        email: "rdrummond22@networksolutions.com",
        role: "barangay",
        barangay_id: 75,
    },
    {
        username: "hpynn23",
        password: "yY2$x)zjz>)",
        email: "lclements23@state.gov",
        role: "barangay",
        barangay_id: 76,
    },
    {
        username: "cdunkley24",
        password: "pA8!ZKr",
        email: "rzannotti24@merriam-webster.com",
        role: "barangay",
        barangay_id: 77,
    },
    {
        username: "cmatysiak25",
        password: "oW9(O?4n|aQi",
        email: "dhayworth25@nhs.uk",
        role: "barangay",
        barangay_id: 78,
    },
    {
        username: "atynemouth26",
        password: "bA6(JmU/7xKh",
        email: "rbenardette26@google.com.br",
        role: "barangay",
        barangay_id: 79,
    },
    {
        username: "nquilligan27",
        password: "jF1+Jm}8Wvr",
        email: "srobertazzi27@github.com",
        role: "barangay",
        barangay_id: 80,
    },
    {
        username: "gboater28",
        password: "fS4hlec",
        email: "mbushe28@ebay.co.uk",
        role: "barangay",
        barangay_id: 81,
    },
    {
        username: "ckineton29",
        password: "yP0}pE3urd",
        email: "okinningley29@booking.com",
        role: "barangay",
        barangay_id: 82,
    },
    {
        username: "mmordan2a",
        password: "eF9=gG42N+RY",
        email: "aperin2a@craigslist.org",
        role: "barangay",
        barangay_id: 83,
    },
    {
        username: "tshepeard2b",
        password: "qJ3%hOYm8",
        email: "thazelby2b@stanford.edu",
        role: "barangay",
        barangay_id: 84,
    },
    {
        username: "awitter2c",
        password: "sE7.&oY?",
        email: "wkull2c@tripod.com",
        role: "barangay",
        barangay_id: 85,
    },
    {
        username: "estollwerck2d",
        password: "tJ0{GcoIc07h",
        email: "pdibernardo2d@ehow.com",
        role: "barangay",
        barangay_id: 86,
    },
    {
        username: "nbynert2e",
        password: "uI9&%c5>",
        email: "fbuntine2e@quantcast.com",
        role: "barangay",
        barangay_id: 87,
    },
    {
        username: "zhudspeth2f",
        password: "sJ4{O$%Fat#W",
        email: "cbatchelder2f@hp.com",
        role: "barangay",
        barangay_id: 88,
    },
    {
        username: "gcroome2g",
        password: "uJ6oZxEzAG",
        email: "pscurlock2g@ibm.com",
        role: "barangay",
        barangay_id: 89,
    },
    {
        username: "cstubbe2h",
        password: "eZ0!O}Ek1",
        email: "jedinborough2h@creativecommons.org",
        role: "barangay",
        barangay_id: 90,
    },
    {
        username: "ksteane2i",
        password: "wD1{U(I",
        email: "vhalfpenny2i@china.com.cn",
        role: "barangay",
        barangay_id: 91,
    },
    {
        username: "dharm2j",
        password: "tI0$q%",
        email: "iturbitt2j@fda.gov",
        role: "barangay",
        barangay_id: 92,
    },
    {
        username: "mtreher2k",
        password: "eQ3$}Jxyuph",
        email: "kraspel2k@engadget.com",
        role: "barangay",
        barangay_id: 93,
    },
    {
        username: "ccouthard2l",
        password: "wU3@SiV?zzJ",
        email: "lbillison2l@eventbrite.com",
        role: "barangay",
        barangay_id: 94,
    },
    {
        username: "bgurner2m",
        password: "lC4>IVy",
        email: "randreini2m@hugedomains.com",
        role: "barangay",
        barangay_id: 95,
    },
    {
        username: "nchilley2n",
        password: "iS4.$/E",
        email: "bhenke2n@amazon.de",
        role: "barangay",
        barangay_id: 96,
    },
    {
        username: "tlengthorn2o",
        password: "pP4+OSRd})(_",
        email: "hkleewein2o@yandex.ru",
        role: "barangay",
        barangay_id: 97,
    },
    {
        username: "bribbens2p",
        password: "cG7+1oOLwv_",
        email: "emattson2p@oracle.com",
        role: "barangay",
        barangay_id: 98,
    },
    {
        username: "grugg2q",
        password: "xB9*S9",
        email: "gstallworth2q@google.com.hk",
        role: "barangay",
        barangay_id: 99,
    },
    {
        username: "gjeandot2r",
        password: "rT4_Rg$3aS",
        email: "jfellowes2r@163.com",
        role: "barangay",
        barangay_id: 100,
    },
    {
        username: "dweigh2s",
        password: "rS5/r730",
        email: "sfasham2s@tinypic.com",
        role: "barangay",
        barangay_id: 101,
    },
    {
        username: "jvillar2t",
        password: "cQ6(Iyp",
        email: "nblackeby2t@vinaora.com",
        role: "barangay",
        barangay_id: 102,
    },
    {
        username: "mcartmail2u",
        password: "fC4`j|",
        email: "coxbury2u@constantcontact.com",
        role: "barangay",
        barangay_id: 103,
    },
    {
        username: "sbree2v",
        password: "xK53Aghjg",
        email: "chillett2v@chron.com",
        role: "barangay",
        barangay_id: 104,
    },
    {
        username: "kstearns2w",
        password: "zB9>gkO4",
        email: "vpayle2w@unesco.org",
        role: "barangay",
        barangay_id: 105,
    },
    {
        username: "mkobpac2x",
        password: "rW6)Xp5@y",
        email: "bbartel2x@ning.com",
        role: "barangay",
        barangay_id: 106,
    },
    {
        username: "femney2y",
        password: "tL9|atC36V",
        email: "sdunniom2y@guardian.co.uk",
        role: "barangay",
        barangay_id: 107,
    },
    {
        username: "aitshak2z",
        password: "qF6@at)IlAio",
        email: "aabsolem2z@typepad.com",
        role: "barangay",
        barangay_id: 108,
    },
    {
        username: "waskwith30",
        password: "rA0!>E",
        email: "smcturlough30@163.com",
        role: "barangay",
        barangay_id: 109,
    },
    {
        username: "kbalharrie31",
        password: "zG0??/jKM",
        email: "tlekeux31@hc360.com",
        role: "barangay",
        barangay_id: 110,
    },
    {
        username: "Guest",
        password: "guest123456",
        email: "guest@guest.com",
        role: "guest",
        barangay_id: 111,
    },
];